---
header-includes:
- \usepackage{amssymb}
- \usepackage{color}
- \documentclass{article}
- \usepackage{amsmath}
- \usepackage{setspace}
- \usepackage{xcolor}
- \usepackage{graphicx}
output:
pdf_document: newcommandault
html_document: newcommandault
---
<!-- English character -->
\newcommand{\ua}{{\bf a}} 
\newcommand{\uA}{{\bf A}}
\newcommand{\ub}{{\bf b}} 
\newcommand{\uB}{{\bf B}}
\newcommand{\uc}{{\bf c}}
\newcommand{\uC}{{\bf C}}
\newcommand{\ud}{{\bf d}} 
\newcommand{\uD}{{\bf D}}
\newcommand{\ue}{{\bf e}}
\newcommand{\uE}{{\bf E}}
\newcommand{\uf}{{\bf f}}
\newcommand{\uF}{{\bf F}}
\newcommand{\ug}{{\bf g}}
\newcommand{\uG}{{\bf G}}
\newcommand{\uh}{{\bf h}}
\newcommand{\uH}{{\bf H}} 
\newcommand{\ui}{{\bf i}}
\newcommand{\uI}{{\bf I}} 
\newcommand{\uj}{{\bf j}}
\newcommand{\uJ}{{\bf J}}
\newcommand{\uk}{{\bf k}}
\newcommand{\uK}{{\bf K}}
\newcommand{\ul}{{\bf l}}
\newcommand{\uL}{{\bf L}}
\newcommand{\um}{{\bf m}} 
\newcommand{\uM}{{\bf M}}
\newcommand{\un}{{\bf n}}
\newcommand{\uN}{{\bf N}}
\newcommand{\uo}{{\bf o}}
\newcommand{\uO}{{\bf O}}
\newcommand{\up}{{\bf p}}
\newcommand{\uP}{{\bf P}}
\newcommand{\uq}{{\bf q}}
\newcommand{\uQ}{{\bf Q}}
\newcommand{\ur}{{\bf r}}
\newcommand{\uR}{{\bf R}}
\newcommand{\us}{{\bf s}}
\newcommand{\uS}{{\bf S}}
\newcommand{\ut}{{\bf t}}
\newcommand{\uT}{{\bf T}}
\newcommand{\uu}{{\bf u}}
\newcommand{\uU}{{\bf U}}
\newcommand{\uv}{{\bf v}}
\newcommand{\uV}{{\bf V}}
\newcommand{\uw}{{\bf w}}
\newcommand{\uW}{{\bf W}}
\newcommand{\ux}{{\bf x}}
\newcommand{\uX}{{\bf X}} 
\newcommand{\uy}{{\bf y}} 
\newcommand{\uY}{{\bf Y}}
\newcommand{\uz}{{\bf z}}
\newcommand{\uZ}{{\bf Z}}
<!-- Greek character -->
\newcommand\ualpha{{\boldsymbol \alpha}}
\newcommand{\ubeta}{{\boldsymbol \beta}} 
\newcommand{\bg}{{\boldsymbol \gamma}}
\newcommand{\bG}{{\boldsymbol \Gamma}}
\newcommand{\udelta}{{\boldsymbol \delta}}
\newcommand{\uDelta}{{\boldsymbol \Delta}}
\newcommand{\uepsilon}{{\boldsymbol \epsilon}}
\newcommand{\uvarepsilon}{{\boldsymbol \varepsilon}}
\newcommand{\uzeta}{{\boldsymbol \zeta}}
\newcommand{\ueta}{{\boldsymbol \eta}} 
\newcommand{\utheta}{{\boldsymbol \theta}}
\newcommand{\uvartheta}{{\boldsymbol \vartheta}}
\newcommand{\uTheta}{{\boldsymbol \Theta}}
\newcommand{\uiota}{{\boldsymbol \iota}}
\newcommand{\ukappa}{{\boldsymbol \kappa}}
\newcommand{\ulambda}{{\boldsymbol \lambda}}
\newcommand{\uLambda}{{\boldsymbol \Lambda}}
\newcommand{\umu}{{\boldsymbol \mu}} 
\newcommand{\unu}{{\boldsymbol \nu}}
\newcommand{\uxi}{{\boldsymbol \xi}}
\newcommand{\uXi}{{\boldsymbol \Xi}}
\newcommand{\uomicron}{{\boldsymbol \omicron}}
\newcommand{\uOmicron}{{\boldsymbol \Omicron}}
\newcommand{\upi}{{\boldsymbol \pi}}
\newcommand{\uPi}{{\boldsymbol \Pi}}
\newcommand{\urho}{{\boldsymbol \rho}}
\newcommand{\uvarrho}{{\boldsymbol \varrho}}
\newcommand{\usigma}{{\boldsymbol \sigma}}
\newcommand{\uSigma}{{\boldsymbol \Sigma}}
\newcommand{\utau}{{\boldsymbol \tau}}
\newcommand{\uupsilon}{{\boldsymbol \upsilon}}
\newcommand{\uUpsilon}{{\boldsymbol \Upsilon}}
\newcommand{\uphi}{{\boldsymbol \phi}}
\newcommand{\uvarphi}{{\boldsymbol \varphi}}
\newcommand{\uPhi}{{\boldsymbol \Phi}}
\newcommand{\uchi}{{\boldsymbol \chi}}
\newcommand{\upsi}{{\boldsymbol \psi}}
\newcommand{\uPsi}{{\boldsymbol \Psi}}
\newcommand{\uomega}{{\boldsymbol\omega}}
\newcommand{\uOmega}{{\boldsymbol\Omega}}
<!-- math sign -->
\newcommand{\0}{{\boldsymbol 0}} 
\newcommand{\1}{{\boldsymbol 1}} 
\newcommand{\T}{{\top}} 
\newcommand{\diag}{{\rm diag}} 
<!-- others -->
\newcommand\nbd{{\rm nbd}}



# Statistics {#stats}

## Bayesian Linear Model

## Project 1

## Project 2

## Project 3
Let a $(k+1)\times (k+1)$ matrix $\uM$ be partitioned in to a block form:
$$
\uM = \left[\begin{array}{cc}\uA&\ub\\\ub^{\T}&c\end{array}\right],
$$
where $\uA$ is $k\times k$ matrix, $\ub$ is $k\times 1$ vector, and $c$ is a scalar. Then
$$
\uM^{-1} = \left[\begin{array}{cc}\uA^{-1}+m^{-1}\uA^{-1}\ub\ub^{\T}\uA^{-1}&-m^{-1}\uA^{-1}\ub\\-m^{-1}\ub^{\T}\uA^{-1}&m^{-1}\end{array}\right],
$$
where $m=c - \ub^{\T}\uA^{-1}\ub$.

Let $\uA = \uX_\bg^{\T}\uX_\bg + \lambda^{-1}\uI_{|\bg|}$, $\ub = \uX_\bg^{\T}\ux_j$, and $c = \ux_j^{\T}\ux_j + \lambda^{-1}$.
\begin{eqnarray*}
\hat\ubeta_{\bg^{+j}} &=& (\uX_{\bg^{+j}}^{\T}\uX_{\bg^{+j}}+\lambda^{-1}\uI_{|{\bg^{+j}}|})^{-1}\uX_{\bg^{+j}}^{\T}\uy\\
&=&\left[\begin{array}{cc} \uX_\bg^{\T}\uX_\bg + \lambda^{-1}\uI_{|\bg|} & \uX_\bg^{\T}\ux_j \\ \ux_j^{\T}\uX_\bg & \ux_j^{\T}\ux_j + \lambda^{-1} \end{array}\right]^{-1}\left[\begin{array}{c}\uX_\bg^{\T}\\\ux_j^{\T}\end{array}\right]\uy\\
&=&\left[\begin{array}{cc}\uA&\ub\\\ub^{\T}&c\end{array}\right]^{-1}\left[\begin{array}{c}\uX_\bg^{\T}\\\ux_j^{\T}\end{array}\right]\uy\\
&=&\left[\begin{array}{cc}\uA^{-1}+m^{-1}\uA^{-1}\ub\ub^{\T}\uA^{-1}&-m^{-1}\uA^{-1}\ub\\-m^{-1}\ub^{\T}\uA^{-1}&m^{-1}\end{array}\right]^{-1}\left[\begin{array}{c}\uX_\bg^{\T}\\\ux_j^{\T}\end{array}\right]\uy
\end{eqnarray*}
Therefore, 
\begin{eqnarray*}
m &=& \ux_j\ux_j^{\T}+\lambda^{-1} - \ux_j^{\T}\uX_\bg(\uX_\bg^{\T}\uX_\bg + \lambda^{-1}\uI_{|\bg|})^{-1}\uX_\bg\ux_j\\
&=& \lambda^{-1} + \ux_j(\uI_n - \uX_\bg(\uX_\bg^{\T}\uX_\bg + \lambda^{-1}\uI_{|\bg|})^{-1}\uX_\bg^{\T})\ux_j^{\T}\\
&=& \lambda^{-1} + \ux_j(\uI_n - \uP_\bg)\ux_j^{\T}\\
\hat\beta_j &=& (-m^{-1}\ub^{\T}\uA^{-1}\uX_\bg^{\T} + m^{-1}\ux_j^{\T})\uy\\
&=&m^{-1}(\ux_j^{\T} - \ub^{\T}\uA^{-1}\uX_\bg^{\T})\uy\\
&=& m^{-1}(\ux_j^{\T} - \ux_j^{\T}\uX_\bg(\uX_\bg^{\T}\uX_\bg + \lambda^{-1}\uI_{|\bg|})^{-1}\uX_\bg^{\T})\uy\\
&=& m^{-1}\ux_j^{\T}(\uI_n - \uX_\bg(\uX_\bg^{\T}\uX_\bg + \lambda^{-1}\uI_{|\bg|})^{-1}\uX_\bg^{\T})\uy\\
&=& m^{-1}\ux_j^{\T}(\uy- \uX_\bg(\uX_\bg^{\T}\uX_\bg + \lambda^{-1}\uI_{|\bg|})^{-1}\uX_\bg^{\T}\uy)\\
&=& m^{-1}\ux_j^{\T}(\uy- \uX_\bg\hat\ubeta_\bg)\\
&=& \frac{\ux_j^{\T}\hat\uepsilon_\bg}{\lambda^{-1} + \ux_j(\uI_n - \uP_\bg)\ux_j^{\T}},
\end{eqnarray*}
where $\hat\ubeta_\bg = (\uX_\bg^{\T}\uX_\bg+\lambda^{-1}\uI_{|\bg|})^{-1}\uX_\bg^{\T}\uy$, $\hat\uepsilon_\bg = \uy -\uX_\bg\hat\ubeta_\bg$, and $\uP_\bg = \uX_{\bg}(\uX_{\bg}^{\T}\uX_{\bg}+\lambda^{-1}\uI_{|{\bg}|})^{-1}\uX_{\bg}^{\T}$. 