# English

## Suits-Season 1-Episode 1

### Vacabulary & Sentense

- get screwed | 搞砸了
- Have I come at a bad time? ｜ 我来得不是时候吗？
- what happened in the interim | 这期间都发生了什么？
- it's last minute bad faith bullshit | 最后时刻不守信用
- honorary vice president | 名誉副总裁
- I don't give a shit | 我不在乎
- get a grasp on what's happened | 掌握(知道)了发生了什么
- title | 头衔
- take away the last shred of his dignity | 让他尊严扫地
- you're mistaken | 你错了。
- the ball is in your court | 该你做决定了
- your balls are in my fist | 你没得选了
- I receive confirmation of a wire transfer from escrow indicating payment in full | 我收到一份由第三分出具的全额付讫的电汇凭据。escrow: 暂由第三者保存的契据
- pansy v.s. manhood | 娘气的 v.s 男子气概
- fire drill | 消防演习
- what did you get me?  - what I said I was gonna get you | 你给我考了多少分？就跟我之前说的分数
- get one's shit together. | organize oneself so as to be able to deal with or achieve something.
- I almost got caught cheating today. | 我今天差点被活捉
- get stoned/burn bud ｜吸大麻
- pot/marijuana/cannabis/hemp 大麻
- drug dealer
- **vacuum-sealed** bud | 真空包装大麻
- I **take on** real software project.|我**承担**真正的软件项目
- I need someone to **make the drop** | 我需要有人完成交易
- on death row | 死囚区 prison for crimials who have been sentenced to death
- pick up doing sth | 轻而易举做某事
- 你怎么知道他**不会**看那张纸呢？ | How did you know he wouldn't look at that memo?
- 因为被激怒的公牛只盯着红色斗蓬|because the **charing bull** always look at red **cape**.
- 包在我身上 | consider it done
- Then you are officialy **dismissed**. | 准予离开
- I **get off** at **ten past** | 我**十点后下班**
- workout: the activity of exerting your muscles in various ways to keep fit 锻炼
- I can **make you** breakfast | 我给你做了早餐
- she can't count it towards next year's quota | 她不能将其计入明年的指标了。
- 你的日子过得很艰难｜the life has been hard for you
- 你会不遗余力地做事情 | you're gonna start living up to your potential.


- this deal wasn't in jeopardy
- I don't what him around; He wouldn't be around
- operate/deal in bad faith
- I see how it is
- instead of working Cooper, you're working me.
- do I know you from somewhere?
- You in cap
- sap motivation; sap confidence; sap strength.
- I'm so glad you stopped by
- It will **take some stress off** Trevor
- **I don't normally do this**

## Bible

### Matthew

#### Chapter 11

- 6 凡不因我跌倒的就有福了

> Blessed is anyone who does not stumble on account of me.

- 11 凡妇人所生的，没有一个兴起来大过施洗约翰的；然而天国里最小的比他还大。

> Among those of women there has not risen['rɪzn] anyone greater than John the Baptist; yet he who is least in the kingdom of heaven is greater than he.

- 12 从施洗约翰的时候到如今，天国是努力进入的，努力的人就得着了。

> From the days of John the Baptist until now, the kingdom of heaven has benn forcefully advancing, and forceful men lay hold of it.

- 17 我们向你们举哀，你们不捶胸

> we sany a dirge, and you did not mourn.

- 19 人子来了，也吃也喝，人又说他是贪食好酒的人

> the Son of man came eating and drinking, and they say, "Here is a glutton and a drunkard".

21 因为在你们中间所行的异能，若行在推罗、西顿，他们早已披麻蒙灰悔改了。

> If the miracles that were performed in you had been performed in Tyre and Sidon, they would have repented long ago in sackcloth and ashes.

- 24 它还可以存到今日。但告诉你们：当审判的日子，所多玛所受的，比你还容易受呢！

> it would have remained to this day. But I tell you it will be more bearable for Sodom on the day of judgement than for you.

- 28 凡劳苦担重担的人，可以到我这里来，我就使你们得安息。

> Come to me, all you who are weary and burdened, and I will give you rest.

#### Chapter 12
- 陈设饼 ｜ consecrated bread
- 犯了安息日 | desecrate the Sabbath
- “我喜爱怜恤，不喜爱祭祀”。你们若明白这话的意思，就不将无罪的当作有罪的了。

> If you had known there words mean, "I desire mercy, not sacrifice", you will not condemn the innocent.

- a shriveled hand [ˈʃrɪvl]
- looking for a reason to bring charges against Jesus.
- 你们中间谁有一只羊，当安息日掉在坑里，不把它抓住、拉上来呢？

> If any of you has a sheep and it falls into a pit on the Sabbath, will you not take hold of it and lite it out?

- 我要将我的灵赐给他；他必将公理传给外邦

> I will put my spirit on him, and he will proclaim justice to nations.

- 他不争竞，不喧嚷； | He will not quarrel or cry out.
- 20 压伤的芦苇，他不折断；将残的灯火，他不吹来；等他旅行公理，叫公理得胜。

> A bruised reed he will not break, and a smoldering wick he will not snuff out, till he has brought justice through to victory.

- 21 外邦人都要仰望他的名 | In his name the nations will put their hope.

- 25 凡一国自相纷争，就成为荒城 | Every kingdom divided against itself will be ruined.
- 29 人怎能进壮士的家里，抢夺他的家具呢？除非先捆住那壮士，才可以抢夺他的家财。

> Or again, how can anyone enter a strong man's house and carry off his possessions unless he first ties up the strong man? Then he can plunder his house.

- 34 因为心里所充满的，口里就说出来了 ｜ For the mouth speaks what the heart is full of.
- 35 善人从他心里所存的善就发出善来；| A good man brings good things out of the good stored up in him.
- 36 凡人所说的闲话，当审判的日子，必要句句供出来；| everyone will have to give account on the day of judgement for every empty word they have spoken.
- 37 因为要凭你的话定你为义，也要凭你的话定你有罪。| For by your words you will be acquitted, and by your words you will be condemned.
- impure spirit | 污鬼

#### Chapter 19
- 6 所以神所配合的，人不可分开 | Therefore what God has joined together, let no one separate.
- 9 我告诉你们，凡休妻另娶的，若不是为淫乱的缘故，就是犯奸淫了；有人娶那被休的妇人，也是犯奸淫了。

> I tell you that anyone who divorces his wife, except for sexual immorality, and marries another woman commits adultery.

- 耶稣说：“这话不是人都能领受的，惟独赐给谁，谁才能领受”

> Jesus replied: "not everyone can accept this word, but only those to whom it has been given"

- 按手祷告 | place one's hands on sb and pray for sb.
- 14 for the kingdom of heaven belongs to such as these. | 因为在天国的，正是这样的人.
- 遵守诫命 | keep the commandments
- 做假见证 | give false testimony
- 22 少年人听见这话，就忧忧愁愁地走了，因为他的产业很多。

> When the young man heard this, he went away sad, because he had great wealth.

- 28 耶稣说：“我实在告诉你们，你们这跟从我的人，到复兴的时候，人子坐在他荣耀的宝座上，你们也要坐在十二个宝座上，审判以色列十二个支派。”

> Jesus said to them, "Truly I tell you, at the renewal of all things, when the Son of Man sits on his glorious throne, you who have followed me will also sit on the twelve glorious thrones, judging the twelve tribes of Israel"

### Luke

#### Chapter 1
- Elizaeth was batten; and they were both wellalong in years. | 伊利沙伯不生育，两个人又年纪老迈了。

- 24 After this his wife Elizabeth became pregnant and for five month remained in seclusion. |  这些日子以后，他的妻子伊利沙伯怀了孕，就隐藏了五个月。 

- 34 How it will be | 怎么会有这回事呢？

- 38 May it be to me as you have said. | 情愿照你的话成就在我身上。

- 39 hurry to a town

- 48 for he has been mindful of te humble sate of his servant. |因为他顾念他使女的卑微。


### Names

#### Geographical Names
- Bethsaida | 伯赛大
- Capernaum | 迦百农
- Galilee | 加利利
- Judea | 犹太
- Jordan | 约旦
- Korazin | 哥拉汛
- Nineveh | 尼尼微
- Sidon | 西顿
- Sodom | 所多玛
- Tyre | 推罗


#### Persons' Names
- Jonah | 约拿
- Beelzebul | 别西卜
- Zechariah [ˌze-kə-ˈrī-ə] | 撒迦利亚


## Harry potter and the prisoner of Azkaban

- growl

### Chapter 14 Snape's grudge

- a wealth of detail
- Ron was **rather** enjoying the experience. *replace "very"*
- surly [ˈsɜːrli] adj. inclined to anger or bad feelings with overtones of menace
- menace [ˈmenəs] n. 1. something that is a source of danger. 2 a threat or the act of threatening; v. 1. pose a threat to; present a danger to; 2. express a threat either by an utterance or a gesture; 3. act in a threatening manner. 
- chilling adj. so scary as to cause chills and shudders
- leer V-I If someone leers at you, they smile in an unpleasant way, usually because they are sexually interested in you. (挑逗地) 斜瞟 [表不满]
- nip 1. give a small sharp bite to; 2. squeeze tightly between the fingers; 3 sever or remove by pinching or snipping.
- ferret [ˈferɪt]  n. 雪貂;白鼬;
- avert 
  * 1 V-T If you avert something unpleasant, you prevent it from happening. 防止;
  * 2 V-T If you avert your eyes or gaze from someone or something, you look away from them. 转移 (视线)
- they knew better than to accept, because they had too much experience with Hagrid's cooking. 他们不敢接受， 因为他们已经多次领教过海格的厨艺了。
- He look uncharacteristically serious. 他一脸反常。
- doggedly [ˈdɔːɡɪdli] adv. with obstinate determination
- go through a rough time 
- But she is still sticking up for it. 但是她还袒护它
- It's a maniac[ 'meiniæk ]. 它疯了
- Buckbeak **spat** a few ferret bones onto Hagrid's pillow.  
- A large of people **was bunched around** the bulletin board. 一大群人正围在布告栏前
- Ron **cranes** over the **heads/necks**.  vi. 伸着脖子看；迟疑，踌躇
- After what Sirius Black **nearly** did it to you. 在小天狼星差点对你下手之后
- expel
  * 1. V-T If someone is expelled from a school or organization, they are officially told to leave because they have behaved badly. e.g: More than five-thousand high school students have been expelled for cheating.
  * 2. V-T To expel something means to force it out from a container or from your body. 排出. e.g: As the lungs exhale this waste, gas is expelled into the atmosphere.
  
  
## Writing

### formal writing

Add another **public health crisis** to the **toll** of the new coronavirus: **Mounting data** suggests that domestic abuse is **acting like an opportunistic** infection, **flourishing** in the conditions created by the pandemic.

>另一场公共健康危机也该归为新型疫情造成的损失：越来越多的数据表明，家庭暴力如同一种伺机性感染，正在大流行造成的环境中迅速蔓延。

**There was every reason** to believe that the **restrictions imposed to** keep the virus from spreading would have such an effect, said Marianne Hester, a Bristol University sociologist who studies abusive relationships. Domestic violence goes up whenever families spend more time together, such as the Christmas and summer vacations, she said.

>一位研究虐待关系的Bristol大学社会学家，Marianne Hester说，
非常有理由相信为防止病毒传播而实施的限制措施会带来这样的效果。
每当家庭花更多的时间待在一起，例如圣诞节和暑假，家庭暴力就会增加。

Now, with families in lockdown worldwide, hotlines are **lighting up with** abuse reports, leaving governments trying to **address a crisis** that experts say **they should have seen coming**.

The United Nations called on Sunday for urgent action to **combat the worldwide surge** in domestic violence. "I urge all governments to **put women's safety first** as they respond to the pandemic," Secretary General Antonio Guterres wrote on Twitter. 


But governments **largely failed** to prepare for the way the new public health measures would create opportunities for abusers to **terrorize their victims**. Now, many are **scrambling to** offer services to those at risk.




### email writing

- So sorry for not **getting back** to you 
- I am currently working on the paper (as usual I **got sidetracked with** FDA work)
- I have **taken today and tomorrow off** to specifically work on the paper. 
- I will be more **proactive** about **keeping you in the loop**. 
- I'll try to **finish it up** and then **get the clearances**.
- It is attached herewith. 

## others

- He was startled and was gripped by fear. 
- Your wife Elizabeth will bear you a son. | 你妻子伊莉沙伯要给你生一个儿子。
- Art supply stores can be rather **baffling in profusion** of products. | 艺术品供应商店里的产品丰富得可能让人感到莫名其妙。
- exert a strong influence on 
- How are you liking it so far? | 到目前为止，您感觉如何？
- How long have you all lived here?
- Pomeranian [,pɔmə'reiniən]; peekapom
- Do you mind holding for just a second? I'll be right back.
- occasionally [ə-ˈkāzh-nə-lē]
- I have a feeling that regardless of the current political ties, China and Europe will lead in that Industry. | 我觉得无论当前的政治关系如何，中国和欧洲都将在这个行业中处于领先地位。
- Many of the precious metals and many of the greatest developments in the Quantum field have happened in China so I'm trying to learn Chinese.| 量子领域中的许多贵金属和许多最伟大的发展都发生在中国，所以我想学中文。
- Spacedeck | 太空甲板
- Well, I think that it will take several decades until there is a change in leadership. I understand very little about the CCP but as I've read, many of those young activists are being put through the system.
- The way they are being treated is very similar to how many of the civil rights activists were treated.| 对待他们的方式与对待许多民权活动人士的方式非常相似。
- I only hope that they have the courage and strength to endure. 
- By old China I mean the parts of China that are still indigenous, that still practice old customs and rituals. The parts that aren't as highly industrialized as say Beijing or Shanghai.
- From what I understand some places in Shanghai and Hong Kong are actually as affluent as NYC or Chicago.
- Personally, I think the it still sees itself as some kind of acting Monarchy. Like a celestial [[səˈlestʃl]] authority that mirrors the old dynasties of the past.
- Hardworking, loyal, honest, loving, intelligent.
- abominable [əˈbɑːmɪnəbl]  idols ｜可憎之物    ~ Crime;~ coffee 劣质的咖啡
- Baal  ˈbā(-ə)l  Molech ['məulek] 摩洛
- detestable 