
# Recitation

## Good verses

- 从来没有人看见神，只有在父怀里的独生子将他表明出来。No one has ever seen God, but the one and only Son, who is himself God and is in closest relationship with the Father, has made him known. (John 1:18)

- 10 神啊，求你為我造清潔的心，使我裏面重新有正直的(或譯：堅定的)靈。10 Create in me a pure heart, O God, and renew a steadfast spirit within me. (Psalm 51:10)

- 17 神所要的祭就是憂傷的靈； 神啊，憂傷痛悔的心，你必不輕看。17 My sacrifice, O God, is a broken spirit; a broken and contrite heart you, God, will not despise. (Psalm 51:17)

- 约3：19-21 光来到世间，世人因自己的行为是恶的，不爱光倒爱黑暗，定他们的罪就是如此。凡作恶的便恨光，并不来就光，恐怕他的行为受责备；但行真理的必来就光，要显明他所行的是靠神而行。This is the verdict: Light has come into the world, but people loved darkness instead of light because their deeds were evil. 20 Everyone who does evil hates the light, and will not come into the light for fear that their deeds will be exposed. 21  But whoever lives by the truth comes into the light, so that it may be seen plainly that what they have done has been done in the sight of God.

## Good chapters

- 1. Matthew 1:18-24

**Joseph Accepts Jesus as His Son**

18 This is how the birth of Jesus the Messiah came about: His mother Mary was pledged to be married to Joseph, but before they came together, she was found to be pregnant through the Holy Spirit. 19 Because Joseph her husband was faithful to the law, and yet did not want to expose her to public disgrace, he had in mind to divorce her quietly.

20 But after he had considered this, an angel of the Lord appeared to him in a dream and said, “Joseph son of David, do not be afraid to take Mary home as your wife, because what is conceived in her is from the Holy Spirit. 21 She will give birth to a son, and you are to give him the name Jesus, because he will save his people from their sins.”

22 All this took place to fulfill what the Lord had said through the prophet: 23 “The virgin will conceive and give birth to a son, and they will call him Immanuel” (which means “God with us”).

24 When Joseph woke up, he did what the angel of the Lord had commanded him and took Mary home as his wife. 25 But he did not **consummate[ˈkän(t)-sə-ˌmāt] their marriage** until she gave birth to a son. And he gave him the name Jesus.

- Matthew 2 

**The Magi Visit the Messiah**

1 After Jesus was born in Bethlehem in Judea, during the time of King Herod, Magi (2:1 Traditionally wise men) from the east came to Jerusalem 2 and asked, “Where is the one who has been born king of the Jews? We saw his star when it rose and have come to worship him.”
3 When King Herod heard this he was disturbed, and all Jerusalem with him. 4 When he had called together all the people’s chief priests and teachers of the law, he asked them where the Messiah was to be born. 5 “In Bethlehem in Judea,” they replied, “for this is what the prophet has written:
6 "'But you, Bethlehem, in the land of Judah,
are by no means least among the rulers of Judah;
for out of you will come a ruler who will shepherd my people Israel.' (Micah 5:2),"
7 Then Herod called the Magi secretly and found out from them the exact time the star had appeared. 8 He sent them to Bethlehem and said, “Go and search carefully for the child. As soon as you find him, report to me, so that I too may go and worship him.”

9 After they had heard the king, they went on their way, and the star they had seen when it rose went ahead of them until it stopped over the place where the child was. 10 When they saw the star, they were overjoyed. 11 On coming to the house, they saw the child with his mother Mary, and they bowed down and worshiped him. Then they opened their treasures and presented him with gifts of gold, frankincense [ˈfraŋ-kən-ˌsen(t)s] and myrrh. 12 And having been warned in a dream not to go back to Herod, they returned to their country by another route.

- MATTHEW 5

**Introduction to the Sermon on the Mount**

1 Now when Jesus saw the crowds, he went up on a mountainside and sat down. His disciples came to him, 2 and he began to teach them.

**The Beatitudes**

He said:

3 “Blessed are the poor in spirit,
for theirs is the kingdom of heaven.

4 Blessed are those who mourn,
for they will be comforted.

5 Blessed are the meek,
for they will inherit the earth.

6 Blessed are those who hunger and thirst for righteousness,
for they will be filled.

7 Blessed are the merciful,
for they will be shown mercy.

8 Blessed are the pure in heart,
for they will see God.

9 Blessed are the peacemakers,
for they will be called children of God.

10 Blessed are those who are persecuted because of righteousness,
for theirs is the kingdom of heaven.

11 “Blessed are you when people insult you, persecute you and falsely say all kinds of evil against you because of me. 12 Rejoice and be glad, because great is your reward in heaven, for in the same way they persecuted the prophets who were before you.

**山上寶訓**

1 耶穌看見這許多的人，就上了山，既已坐下，門徒到他跟前來， 2 他就開口教訓他們，說：

**論福**

3 虛心的人有福了！
因為天國是他們的。
4 哀慟的人有福了！
因為他們必得安慰。
5 溫柔的人有福了！
因為他們必承受地土。
6 飢渴慕義的人有福了！
因為他們必得飽足。
7 憐恤人的人有福了！
因為他們必蒙憐恤。
8 清心的人有福了！
因為他們必得見神。
9 使人和睦的人有福了！
因為他們必稱為神的兒子。
10 為義受逼迫的人有福了！
因為天國是他們的。
11 「人若因我辱罵你們，逼迫你們，捏造各樣壞話毀謗你們，你們就有福了！ 12 應當歡喜快樂，因為你們在天上的賞賜是大的。在你們以前的先知，人也是這樣逼迫他們。」

- 2. Luke 1:67-80

**Zechariah’s Song**

67 His father Zechariah [ˌze-kə-ˈrī-ə] was filled with the Holy Spirit and prophesied:

68 “Praise be to the Lord, the God of Israel, because he has come to his people and redeemed them.
69 He has raised up a horn (Horn here symbolizes a strong king) of salvation for us
in the house of his servant David 70 (as he said through his holy prophets of long ago), 71 salvation from our enemies and from the hand of all who hate us—
72 to show mercy to our ancestors and to remember his holy covenant,
73 the oath he swore to our father Abraham:
74 to rescue us from the hand of our enemies, and to enable us to serve him without fear
75 in holiness and righteousness before him all our days.
76 And you, my child, will be called a prophet of the Most High; for you will go on before the Lord to prepare the way for him,
77 to give his people the knowledge of salvation through the forgiveness of their sins,
78 because of the tender mercy of our God, by which the rising sun will come to us from heaven
79 to shine on those living in darkness and in the shadow of death, to guide our feet into the path of peace.”

80 And the child grew and became strong in spirit (Or in the Spirit;) and he lived in the wilderness until he appeared publicly to Israel.

- 3. Psalms 51

_For the director of music. A psalm of David. When the prophet Nathan came to him after David had committed adultery with Bathsheba._


1 Have mercy on me, O God, according to your unfailing love; according to your great compassion 
blot out my transgressions. 2 Wash away all my iniquity and cleanse me from my sin. 
3 For I know my transgressions,and my sin is always before me. 4 Against you, you only, have I sinned and done what is evil in your sight; so you are right in your verdict 
and justified when you judge. 5 Surely I was sinful at birth, sinful from the time my mother conceived me. 6 Yet you desired faithfulness even in the womb; you taught me wisdom in that secret place. 7 Cleanse me with hyssop, and I will be clean; wash me, and I will be whiter than snow.  8 Let me hear joy and gladness; let the bones you have crushed rejoice. 
9 Hide your face from my sins and blot out all my iniquity. 10 Create in me a pure heart, O God, and renew a steadfast spirit within me. 11 Do not cast me from your presence 
or take your Holy Spirit from me. 12 Restore to me the joy of your salvation and grant me a willing spirit, to sustain me. 13 Then I will teach transgressors your ways, 
so that sinners will turn back to you. 14 Deliver me from the guilt of bloodshed, O God, 
you who are God my Savior, and my tongue will sing of your righteousness.
15 Open my lips, Lord, and my mouth will declare your praise.  16 You do not delight in sacrifice, or I would bring it; you do not take pleasure in burnt offerings.  17 My sacrifice, O God, is (51:17 Or The sacrifices of God are) a broken spirit; a broken and contrite heart
you, God, will not despise.  18 May it please you to prosper Zion, to build up the walls of Jerusalem.  19 Then you will delight in the sacrifices of the righteous, in burnt offerings offered whole; then bulls will be offered on your altar.


1 神啊，求你按你的慈愛憐恤我！  按你豐盛的慈悲塗抹我的過犯！  2 求你將我的罪孽洗除淨盡， 
並潔除我的罪！  3 因為，我知道我的過犯；  我的罪常在我面前。  4 我向你犯罪，惟獨得罪了你；  在你眼前行了這惡，  以致你責備我的時候顯為公義，  判斷我的時候顯為清正。  5 我是在罪孽裏生的，  在我母親懷胎的時候就有了罪。  6 你所喜愛的是內裏誠實；  你在我隱密處，必使我得智慧。  7 求你用牛膝草潔淨我，我就乾淨；  求你洗滌我，我就比雪更白。  8 求你使我得聽歡喜快樂的聲音，
使你所壓傷的骨頭可以踴躍。  9 求你掩面不看我的罪， 塗抹我一切的罪孽。10 神啊，求你為我造清潔的心，  使我裏面重新有正直的(或譯：堅定的)靈。  11 不要丟棄我，使我離開你的面；  不要從我收回你的聖靈。12 求你使我仍得救恩之樂，  賜我樂意的靈扶持我，13 我就把你的道指教有過犯的人，  罪人必歸順你。  14 神啊，你是拯救我的神；  求你救我脫離流人血的罪！  我的舌頭就高聲歌唱你的公義。  15 主啊，求你使我嘴唇張開，  我的口便傳揚讚美你的話！  16你本不喜愛祭物，若喜愛，我就獻上； 
燔祭，你也不喜悅。  17 神所要的祭就是憂傷的靈； 神啊，憂傷痛悔的心，你必不輕看。 18 求你隨你的美意善待錫安，  建造耶路撒冷的城牆。  19 那時，你必喜愛公義的祭  和燔祭並全牲的燔祭； 
那時，人必將公牛獻在你壇上。


- Psalm 23

> A psalm of David.  
1 The Lord is my shepherd, I lack nothing.  
2 He makes me lie down in green pastures, he leads me beside quiet waters, 
3 he refreshes my soul. He guides me along the right paths for his name’s sake.  
4 Even though I walk through the darkest valley, (Or the valley of the shadow of death)  
I will fear no evil, for you are with me; your rod and your staff, they comfort me.  
5 You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows.  
6 Surely your goodness and love will follow me all the days of my life, and I will dwell in the house of the Lord forever.

>1耶和華是我的牧者，我必不致缺乏。
2他使我躺臥在青草地上，領我在可安歇的水邊。
3他使我的靈魂甦醒，為自己的名引導我走義路。
4我雖然行過死蔭的幽谷，也不怕遭害，因為你與我同在；你的杖，你的竿，都安慰我。
5在我敵人面前，你為我擺設筵席；你用油膏了我的頭，使我的福杯滿溢。
6我一生一世必有恩惠慈愛隨着我；我且要住在耶和華的殿中，直到永遠。

<!--
- PHILIPPIANS 2:1-18
**He Took on the Status of a Slave**

1-4 If you’ve gotten anything at all out of following Christ, if his love has made any difference in your life, if being in a community of the Spirit means anything to you, if you have a heart, if you care—then do me a favor: Agree with each other, love each other, be deep-spirited friends. Don’t push your way to the front; don’t sweet-talk your way to the top. Put yourself aside, and help others get ahead. Don’t be obsessed with getting your own advantage. Forget yourselves long enough to lend a helping hand.

5-8 Think of yourselves the way Christ Jesus thought of himself. He had equal status with God but didn’t think so much of himself that he had to cling to the advantages of that status no matter what. Not at all. When the time came, he set aside the privileges of deity and took on the status of a slave, became human! Having become human, he stayed human. It was an incredibly humbling process. He didn’t claim special privileges. Instead, he lived a selfless, obedient life and then died a selfless, obedient death—and the worst kind of death at that—a crucifixion.
9-11 Because of that obedience, God lifted him high and honored him far beyond anyone or anything, ever, so that all created beings in heaven and on earth—even those long ago dead and buried—will bow in worship before this Jesus Christ, and call out in praise that he is the Master of all, to the glorious honor of God the Father.

**Rejoicing Together**

12-13 What I’m getting at, friends, is that you should simply keep on doing what you’ve done from the beginning. When I was living among you, you lived in responsive obedience. Now that I’m separated from you, keep it up. Better yet, redouble your efforts. Be energetic in your life of salvation, reverent and sensitive before God. That energy is God’s energy, an energy deep within you, God himself willing and working at what will give him the most pleasure.
14-16 Do everything readily and cheerfully—no bickering, no second-guessing allowed! Go out into the world uncorrupted, a breath of fresh air in this squalid and polluted society. Provide people with a glimpse of good living and of the living God. Carry the light-giving Message into the night so I’ll have good cause to be proud of you on the day that Christ returns. You’ll be living proof that I didn’t go to all this work for nothing.
17-18 Even if I am executed here and now, I’ll rejoice in being an element in the offering of your faith that you make on Christ’s altar, a part of your rejoicing. But turnabout’s fair play—you must join me in my rejoicing. Whatever you do, don’t feel sorry for me.-->

腓立比书 2:1-18
  
**以基督的心為心**

1 所以，在基督裏若有甚麼勸勉，愛心有甚麼安慰，聖靈有甚麼交通，心中有甚麼慈悲憐憫， 2 你們就要意念相同，愛心相同，有一樣的心思，有一樣的意念，使我的喜樂可以滿足。 3 凡事不可結黨，不可貪圖虛浮的榮耀；只要存心謙卑，各人看別人比自己強。 4 各人不要單顧自己的事，也要顧別人的事。
5 你們當以基督耶穌的心為心：
6 他本有神的形像，
不以自己與神同等為強奪的；
7 反倒虛己，
取了奴僕的形像，
成為人的樣式；
8 既有人的樣子，就自己卑微，
存心順服，以至於死，
且死在十字架上。
9 所以，神將他升為至高，
又賜給他那超乎萬名之上的名，
10 叫一切在天上的、地上的，和地底下的，
因耶穌的名無不屈膝，
11 無不口稱「耶穌基督為主」，
使榮耀歸與父神。
在這世上像明光照耀
12 這樣看來，我親愛的弟兄，你們既是常順服的，不但我在你們那裏，就是我如今不在你們那裏，更是順服的，就當恐懼戰兢做成你們得救的工夫。 13 因為你們立志行事都是神在你們心裏運行，為要成就他的美意。 14 凡所行的，都不要發怨言，起爭論， 15 使你們無可指摘，誠實無偽，在這彎曲悖謬的世代作神無瑕疵的兒女。你們顯在這世代中，好像明光照耀， 16 將生命的道表明出來，叫我在基督的日子好誇我沒有空跑，也沒有徒勞。 17 我以你們的信心為供獻的祭物，我若被澆奠在其上，也是喜樂，並且與你們眾人一同喜樂。 18 你們也要照樣喜樂，並且與我一同喜樂。

- Nehemiah 9:6

You alone are the Lord. You made the heavens, even the highest heavens, and all their starry host, the earth and all that is on it, the seas and all that is in them. You give life to everything, and the multitudes of heaven worship you.
「你，惟獨你是耶和華！你造了天和天上的天，並天上的萬象，地和地上的萬物，海和海中所有的；這一切都是你所保存的。天軍也都敬拜你。
